In [12]:
import torch

In [18]:
# Q1. [2, 3] 형태의 Tensor를 [1, 2, 3] 형태로 변경하기
a = torch.randint(10, (2, 3))
b = a.unsqueeze(0)
print(f"a:\n{a}\nb:\n{b}")
print("-" * 30)

# Q2. [2, 1, 3] 형태의 Tensor를 [2, 3] 형태로 변경하기
a = torch.randint(10, (2, 1, 3))
b = a.squeeze(1)
print(f"a:\n{a}\nb:\n{b}")
print("-" * 30)

# Q3. [4, 2, 3] 형태의 Tensor를 [4, 6] 형태로 변경하기
a = torch.randint(10, (4, 2, 3))
b = a.view(4, 6)
print(f"a:\n{a}\nb:\n{b}")
print("-" * 30)

# Q4. [4, 2, 3] 형태의 Tensor를 [3, 2, 4] 형태로 변경하기
a = torch.randint(10, (4, 2, 3))
b = a.permute(2, 1, 0)
print(f"a:\n{a}\nb:\n{b}")
print("-" * 30)

# Q5. [2, 3] 형태의 두 텐서(혹은 리스트 등)을 [2, 6] 형태로 붙이기
a = torch.randint(10, (2, 3))
b = torch.randint(10, (2, 3))
c = torch.cat((a, b), dim=1)
print(f"a:\n{a}\nb:\n{b}\nc:\n{c}")
print("-" * 30)

# Q6. 2x3 행렬과 3x2 행렬의 곱하기 => 2x2 행렬
a = torch.randint(10, (2, 3))
b = torch.randint(10, (3, 2))
c = torch.matmul(a, b)
print(f"a:\n{a}\nb:\n{b}\nc:\n{c}")
print("-" * 30)

# Q7. 1번에서 계산한 2x2 행렬에 또다른 2x2 행렬 더하기
d = torch.randint(10, (2, 2))
e = c + d
print(f"c:\n{c}\nd:\n{d}\ne:\n{e}")
print("-" * 30)

# Q8. 2번에서 계산한 2x2 행렬 각 열에 길이가 2인 열벡터 더하기
f = torch.randint(10, (2,))
g = e + f.unsqueeze(1)
print(f"e:\n{e}\nf:\n{f}\ng:\n{g}")
print("-" * 30)

# Q9. Q3에서 계산한 2x2 행렬 각 원소에 스칼라 값 곱하기
h = 3
i = g * h
print(f"g:\n{g}\nh:\n{h}\ni:\n{i}")
print("-" * 30)

a:
tensor([[7, 8, 4],
        [8, 3, 7]])
b:
tensor([[[7, 8, 4],
         [8, 3, 7]]])
------------------------------
a:
tensor([[[0, 7, 8]],

        [[1, 0, 1]]])
b:
tensor([[0, 7, 8],
        [1, 0, 1]])
------------------------------
a:
tensor([[[8, 2, 1],
         [7, 0, 7]],

        [[3, 5, 6],
         [6, 8, 8]],

        [[4, 5, 6],
         [7, 2, 0]],

        [[7, 8, 4],
         [2, 3, 4]]])
b:
tensor([[8, 2, 1, 7, 0, 7],
        [3, 5, 6, 6, 8, 8],
        [4, 5, 6, 7, 2, 0],
        [7, 8, 4, 2, 3, 4]])
------------------------------
a:
tensor([[[2, 4, 9],
         [8, 0, 8]],

        [[2, 5, 6],
         [1, 3, 0]],

        [[2, 0, 9],
         [9, 8, 7]],

        [[2, 9, 8],
         [2, 2, 2]]])
b:
tensor([[[2, 2, 2, 2],
         [8, 1, 9, 2]],

        [[4, 5, 0, 9],
         [0, 3, 8, 2]],

        [[9, 6, 9, 8],
         [8, 0, 7, 2]]])
------------------------------
a:
tensor([[3, 6, 1],
        [4, 4, 6]])
b:
tensor([[7, 0, 2],
        [8, 9, 9]])
c:
tensor([