# 과제 목표

1. NumPy의 array 형의 사용법 숙지
2. PyTorch Tensor 형의 사용법 숙지

# NumPy arrays

NumPy는 행렬 연산을 쉽게 하기 위하여 자주 사용하는 파이썬 라이브러리로, 딥러닝 뿐만 아니라 데이터 분석 등 널리 사용되고 있습니다. 매우 다양한 연산자 및 기능을 지원하고 있으며, 자세한 내용은 공식 document에서 쉽게 찾아볼 수 있습니다.

📌 **Install**

Colab에는 기본적으로 NumPy가 설치되어 있지만, 개인 컴퓨터에서 설치한다면 `pip install numpy`로 간단히 설치할 수 있습니다.

📌 **Import NumPy**

Python에서 사용하기 위하여 라이브러리를 불러올 때는 `import numpy as np`로 합니다. `np`로 줄여 쓰는 것이 convention입니다.

📌 앞으로 NumPy의 array는 `ndarray`라고 줄여 부르겠습니다.

😎 **추가자료**
- [NumPy Document (API References)](https://numpy.org/doc/stable/reference/index.html)
- [NumPy 연습 문제 모음](https://github.com/rougier/numpy-100)

In [ ]:
import numpy as np

In [ ]:
"""array 생성하기 (기본): 원하는 차원의 리스트를 전달하여 생성 가능"""
# 1차원
arr1 = np.array([1, 2, 3])
# 2차원
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
# 3차원
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [ ]:
"""행렬 정보 확인하기"""
print(f"Shape of arr3: {arr3.shape}") # 형태 (크기), output: (2, 2, 3)
print(f"Type of arr3: {arr3.dtype}") # 자료형, output: int64 (colab), int32 (local)

Shape of arr3: (2, 2, 3)
Type of arr3: int64


In [ ]:
"""특정 array 생성하기: 미리 정의된 메서드에 원하는 행렬 크기를 전달하여 생성 가능"""
# 모두 0로 채운 배열
zero_arr = np.zeros((3, 3)) # 3x3 행렬
# 모두 1로 채운 배열
one_arr = np.ones((2, 4)) # 2x4 행렬
# 랜덤 수로 채운 배열 (0~1 난수)
rand_arr = np.random.rand(5, 5) # 5x5 행렬
# 랜덤 정수로 채운 배열
rand_int_arr = np.random.randint(-5, 6, (2, 2)) # 2x2 행렬, -5 ~ 5 사이의 난수 생성

In [ ]:
"""인덱싱: 인덱스가 3, 5인 요소만 가져오기"""
arr = np.array([4, 1, 6, 2, 0, 7])
print(f"Elements of which indices are 3 and 5: {arr[[3, 5]]}") # output: [2, 7]

Elements of which indices are 3 and 5: [2 7]


In [ ]:
"""행렬 연산하기"""

arr1 = np.random.randint(0, 5, (2, 3))
arr2 = np.random.randint(0, 5, (2, 3))

# 두 행렬의 합, 차
arr3 = arr1 + arr2
print("arr1 + arr2 = \n", arr3) # output: (2, 3) 행렬
arr4 = arr1 - arr2
print("arr1 - arr2 = \n", arr4) # output: (2, 3) 행렬

# 두 행렬의 곱
# 아래 두 함수는 3차원 이상의 행렬 곱에서 다른 결과를 보임
# 참고: ndarray.T 는 행렬의 행과 열을 바꾸는 transpose 연산
arr5 = np.dot(arr1, arr2.T) # 내적
arr6 = np.matmul(arr1, arr2.T) # 행렬 곱
print("Multiplication of arr1 and arr2 = ")
print(arr5) # output: (2, 2) 행렬
print(arr6) # output: (2, 2) 행렬

# Broadcast: 행렬 * 상수를 수행하면 행렬의 각 요소에 상수를 곱하는 등 특정 값/벡터의 broadcast 연산 지원
arr7 = np.array([1, 2, 3]) * 10
print("arr7 = \n", arr7) # output: [10, 20, 30]

# 평균 계산
avg = arr7.mean()
print("Average of arr7: ", avg) # output: 20.0

# 전치
trans = arr1.T
print(f"Transpose of arr1: (shape - {trans.shape})\n", trans) # output: (3, 2) 행렬

arr1 + arr2 = 
 [[3 4 7]
 [1 1 5]]
arr1 - arr2 = 
 [[-1  2  1]
 [ 1  1  1]]
Multiplication of arr1 and arr2 = 
[[17  8]
 [12  6]]
[[17  8]
 [12  6]]
arr7 = 
 [10 20 30]
Average of arr7:  20.0
Transpose of arr1: (shape - (3, 2))
 [[1 1]
 [3 1]
 [4 3]]


# PyTorch Tensor

Tensor는 NumPy의 array와 작동 방식과 제공하는 연산이 유사합니다. 또한 공식문서가 매우 잘 정리되어 있으니 검색하여 모르는 내용을 찾아보기 쉽습니다.

📌 Install

PyTorch 역시 Colab에서는 기본적으로 설치되어 있습니다. 컴퓨터에 설치 시 `pip install pytorch`로 가능합니다.

📌 Import PyTorch

불러올 때는 `import torch`를 기본으로 하며, 추후 다양한 API를 사용할 때마다 상세 import를 추가적으로 수행하기도 합니다.

😎 **추가자료**
- [PyTorch Document](https://pytorch.org/docs/stable/torch.html#tensors)
- [PyTorch Official Tutorial - Introduction to PyTorch Tensors](https://pytorch.org/tutorials/beginner/introyt/tensors_deeper_tutorial.html)


Local에서 GPU를 사용할 수 있다면 GPU를 사용할 수 있도록 준비해주세요.

Colab에서 GPU를 사용하기 위해선 우측 상단의 '추가 연결 옵션'(RAM, 디스크 statistic 옆 화살표 버튼)에서 [런타임 유형 변경] - [하드웨어 가속기] 에서 GPU로 옵션을 변경해주세요.

In [ ]:
import torch

In [ ]:
# Tensor 선언하기
t1 = torch.tensor([[1, 2, 3], [4, 5, 6]]) # 리스트 or ndarray -> tensor
arr = np.array([1, 2, 3])
t2 = torch.from_numpy(arr) # ndarray -> tensor

# Tensor에서 다른 자료형으로 변경하기
l = t1.tolist() # tensor -> list
arr = t1.numpy() # tensor -> ndarray

# Tensor를 연산할 디바이스 지정하기:
# GPU라면 `device="cuda"` 지정 혹은 `cuda()` 메서드
# CPU라면 `device="cpu"` 지정 혹은 `cpu()` 메서드
t3 = torch.tensor([1, 2], device="cuda")
t3 = t3.to("cuda")
t3 = t3.cpu()

간단하게 Tensor의 크기와 자료형, 처리되는 기기를 조회할 수 있습니다.

참고로, PyTorch에서 데이터(Tensor)를 GPU 연산에 사용하려면 **해당 텐서를 GPU에 올려야 합니다**. 뒤에서 생성할 딥러닝 모델도 마찬가지입니다.

In [ ]:
tensor = torch.rand(2, 4)

print(f"Shape: {tensor.shape}") # 크기
print(f"Data Type: {tensor.dtype}") # 자료형 - 따로 자료형을 지정하지 않는다면 float32가 기본
print(f"Device: {tensor.device}") # 디바이스

Shape: torch.Size([2, 4])
Data Type: torch.float32
Device: cpu


In [ ]:
# 텐서의 기기 변경
tensor = tensor.to('cpu') # 또는 .cpu(), .cuda() 메서드도 있음.
print(f"Device: {tensor.device}")

Device: cpu


## PyToch Tensor 다루기

기본적 Tensor 사용법은 위에서 소개했습니다. 하지만 딥러닝 프로젝트를 개발할 땐 다양한 상황에서 여러 메서드를 사용하는 경우가 많습니다. 아래 각 상황에서 어떻게 문제를 해결하면 좋을지 검색을 통해 답을 완성해봅시다.

- `torch.unsqueeze()`와 `torch.squeeze()`
- `torch.view()`와 `torch.reshape()`
- `torch.concat()`와 `torch.stack()`

In [ ]:
############################################################################
# Req 1-1: PyTorch Tensor 다루기                                            #
############################################################################

################################################################################
# TODO: 아래의 문제를 해결하며 목표한 형태 혹은 값의 행렬 연산을 수행함                  #
################################################################################

# Q1. [2, 3] 형태의 Tensor를 [1, 2, 3] 형태로 변경하기
a = torch.randint(10, (2, 3))
b = a.unsqueeze(0)
print(f"a:\n{a}\nb:\n{b}")
print("-"*30)

# Q2. [2, 1, 3] 형태의 Tensor를 [2, 3] 형태로 변경하기
a = torch.randint(10, (2, 1, 3))
b = a.squeeze(1)
print(f"a:\n{a}\nb:\n{b}")
print("-"*30)

# Q3. [4, 2, 3] 형태의 Tensor를 [4, 6] 형태로 변경하기
a = torch.randint(10, (4, 2, 3))
b = a.reshape(4, 6)
print(f"a:\n{a}\nb:\n{b}")
print("-"*30)

# Q3. [4, 2, 3] 형태의 Tensor를 [3, 2, 4] 형태로 변경하기
a = torch.randint(10, (4, 2, 3))
b = a.reshape(3, 2, 4)
print(f"a:\n{a}\nb:\n{b}")
print("-"*30)

# Q4. [2, 3] 형태의 두 텐서(혹은 리스트 등)을 [2, 6] 형태로 붙이기
a = torch.randint(10, (2, 3))
b = torch.randint(10, (2, 3))
c = torch.cat((a, b), dim=1)
print(f"a:\n{a}\nb:\n{b}\nc:\n{c}")
print("-"*30)

# Q5. 2x3 행렬과 3x2 행렬의 곱하기 => 2x2 행렬
a = torch.randint(10, (2, 3))
b = torch.randint(10, (3, 2))
c = torch.matmul(a, b)
print(f"a:\n{a}\nb:\n{b}\nc:\n{c}")
print("-"*30)

# Q6. 1번에서 계산한 2x2 행렬에 또다른 2x2 행렬 더하기
d = torch.randint(10, (2, 2))
e = c + d
print(f"c:\n{c}\nd:\n{d}\ne:\n{e}")
print("-"*30)

# Q7. 2번에서 계산한 2x2 행렬 각 열에 길이가 2인 열벡터 더하기
f = torch.randint(10, (2,))
g = """Write your code"""
print(f"e:\n{e}\nf:\n{f}\ng:\n{g}")
print("-"*30)

# Q8. Q3에서 계산한 2x2 행렬 각 원소에 스칼라 값 곱하기
h = 3
i = """Write your code"""
print(f"g:\n{g}\nh:\n{h}\ni:\n{i}")
print("-"*30)

a:
tensor([[9, 6, 7],
        [2, 3, 2]])
b:
tensor([[[9, 6, 7],
         [2, 3, 2]]])
------------------------------
a:
tensor([[[4, 7, 0]],

        [[7, 0, 5]]])
b:
tensor([[4, 7, 0],
        [7, 0, 5]])
------------------------------
a:
tensor([[[4, 1, 2],
         [4, 8, 3]],

        [[2, 3, 6],
         [7, 1, 2]],

        [[6, 4, 2],
         [4, 2, 9]],

        [[5, 2, 1],
         [4, 5, 8]]])
b:
tensor([[4, 1, 2, 4, 8, 3],
        [2, 3, 6, 7, 1, 2],
        [6, 4, 2, 4, 2, 9],
        [5, 2, 1, 4, 5, 8]])
------------------------------
a:
tensor([[[6, 5, 0],
         [4, 2, 5]],

        [[5, 2, 3],
         [9, 6, 5]],

        [[0, 2, 0],
         [4, 7, 8]],

        [[1, 4, 3],
         [5, 4, 8]]])
b:
tensor([[[6, 5, 0, 4],
         [2, 5, 5, 2]],

        [[3, 9, 6, 5],
         [0, 2, 0, 4]],

        [[7, 8, 1, 4],
         [3, 5, 4, 8]]])
------------------------------
a:
tensor([[5, 5, 1],
        [8, 7, 7]])
b:
tensor([[0, 3, 1],
        [3, 2, 7]])
c:
tensor([

모델의 학습은 모델 파라미터를 조금씩 변경하며 이뤄집니다. 그 과정에서 학습 오차(loss)를 역전파하며 파라미터 업데이트 값을 결정합니다. 경사하강법(gradient descent)은 오차를 함수로 표현하고 미분하여 그 기울기(gradient)를 구해, 오차의 최솟값 방향으로 파라미터를 업데이트합니다.

PyTorch에서는 미분 계산이 자동적으로 이뤄집니다. 모델 파라미터를 담고 있는 텐서에 자동미분을 하도록 설정하면, 해당 텐서에 대한 미분값(gradient)을 저장합니다.

In [ ]:
# requires_grad 를 설정하면 w에 대한 미분값이 저장됨
w = torch.tensor(1.0, requires_grad=True)

# 테스트를 위한 임의의 수식 정의
x = (w*3)**2

# x를 w로 미분하기: backward() 메서드로 최근 연산부터 차례대로 미분 진행
x.backward()

# 미분값 조회
print(w.grad)